import { ResourceConfig } from './types';

export const NAMESPACED_RESOURCES: Record<string, ResourceConfig> = {
  pods: {
    apiClass: 'CoreV1Api',
    listFn: 'listNamespacedPod',
    getFn: 'readNamespacedPod',
    replaceFn: 'replaceNamespacedPod',
    deleteFn: 'deleteNamespacedPod',
    kind: 'Pod',
    namespaced: true,
  },
  deployments: {
    apiClass: 'AppsV1Api',
    listFn: 'listNamespacedDeployment',
    getFn: 'readNamespacedDeployment',
    replaceFn: 'replaceNamespacedDeployment',
    deleteFn: 'deleteNamespacedDeployment',
    kind: 'Deployment',
    namespaced: true,
  },
  statefulsets: {
    apiClass: 'AppsV1Api',
    listFn: 'listNamespacedStatefulSet',
    getFn: 'readNamespacedStatefulSet',
    replaceFn: 'replaceNamespacedStatefulSet',
    deleteFn: 'deleteNamespacedStatefulSet',
    kind: 'StatefulSet',
    namespaced: true,
  },
  daemonsets: {
    apiClass: 'AppsV1Api',
    listFn: 'listNamespacedDaemonSet',
    getFn: 'readNamespacedDaemonSet',
    replaceFn: 'replaceNamespacedDaemonSet',
    deleteFn: 'deleteNamespacedDaemonSet',
    kind: 'DaemonSet',
    namespaced: true,
  },
  replicasets: {
    apiClass: 'AppsV1Api',
    listFn: 'listNamespacedReplicaSet',
    getFn: 'readNamespacedReplicaSet',
    replaceFn: 'replaceNamespacedReplicaSet',
    deleteFn: 'deleteNamespacedReplicaSet',
    kind: 'ReplicaSet',
    namespaced: true,
  },
  services: {
    apiClass: 'CoreV1Api',
    listFn: 'listNamespacedService',
    getFn: 'readNamespacedService',
    replaceFn: 'replaceNamespacedService',
    deleteFn: 'deleteNamespacedService',
    kind: 'Service',
    namespaced: true,
  },
  ingresses: {
    apiClass: 'NetworkingV1Api',
    listFn: 'listNamespacedIngress',
    getFn: 'readNamespacedIngress',
    replaceFn: 'replaceNamespacedIngress',
    deleteFn: 'deleteNamespacedIngress',
    kind: 'Ingress',
    namespaced: true,
  },
  configmaps: {
    apiClass: 'CoreV1Api',
    listFn: 'listNamespacedConfigMap',
    getFn: 'readNamespacedConfigMap',
    replaceFn: 'replaceNamespacedConfigMap',
    deleteFn: 'deleteNamespacedConfigMap',
    kind: 'ConfigMap',
    namespaced: true,
  },
  secrets: {
    apiClass: 'CoreV1Api',
    listFn: 'listNamespacedSecret',
    getFn: 'readNamespacedSecret',
    replaceFn: 'replaceNamespacedSecret',
    deleteFn: 'deleteNamespacedSecret',
    kind: 'Secret',
    namespaced: true,
  },
  pvcs: {
    apiClass: 'CoreV1Api',
    listFn: 'listNamespacedPersistentVolumeClaim',
    getFn: 'readNamespacedPersistentVolumeClaim',
    replaceFn: 'replaceNamespacedPersistentVolumeClaim',
    deleteFn: 'deleteNamespacedPersistentVolumeClaim',
    kind: 'PersistentVolumeClaim',
    namespaced: true,
  },
  serviceaccounts: {
    apiClass: 'CoreV1Api',
    listFn: 'listNamespacedServiceAccount',
    getFn: 'readNamespacedServiceAccount',
    replaceFn: 'replaceNamespacedServiceAccount',
    deleteFn: 'deleteNamespacedServiceAccount',
    kind: 'ServiceAccount',
    namespaced: true,
  },
  roles: {
    apiClass: 'RbacAuthorizationV1Api',
    listFn: 'listNamespacedRole',
    getFn: 'readNamespacedRole',
    replaceFn: 'replaceNamespacedRole',
    deleteFn: 'deleteNamespacedRole',
    kind: 'Role',
    namespaced: true,
  },
  rolebindings: {
    apiClass: 'RbacAuthorizationV1Api',
    listFn: 'listNamespacedRoleBinding',
    getFn: 'readNamespacedRoleBinding',
    replaceFn: 'replaceNamespacedRoleBinding',
    deleteFn: 'deleteNamespacedRoleBinding',
    kind: 'RoleBinding',
    namespaced: true,
  },
  networkpolicies: {
    apiClass: 'NetworkingV1Api',
    listFn: 'listNamespacedNetworkPolicy',
    getFn: 'readNamespacedNetworkPolicy',
    replaceFn: 'replaceNamespacedNetworkPolicy',
    deleteFn: 'deleteNamespacedNetworkPolicy',
    kind: 'NetworkPolicy',
    namespaced: true,
  },
  jobs: {
    apiClass: 'BatchV1Api',
    listFn: 'listNamespacedJob',
    getFn: 'readNamespacedJob',
    replaceFn: 'replaceNamespacedJob',
    deleteFn: 'deleteNamespacedJob',
    kind: 'Job',
    namespaced: true,
  },
  cronjobs: {
    apiClass: 'BatchV1Api',
    listFn: 'listNamespacedCronJob',
    getFn: 'readNamespacedCronJob',
    replaceFn: 'replaceNamespacedCronJob',
    deleteFn: 'deleteNamespacedCronJob',
    kind: 'CronJob',
    namespaced: true,
  },
  events: {
    apiClass: 'CoreV1Api',
    listFn: 'listNamespacedEvent',
    getFn: 'readNamespacedEvent',
    replaceFn: 'replaceNamespacedEvent',
    deleteFn: 'deleteNamespacedEvent',
    kind: 'Event',
    namespaced: true,
  },
};

export const CLUSTER_SCOPED_RESOURCES: Record<string, ResourceConfig> = {
  nodes: {
    apiClass: 'CoreV1Api',
    listFn: 'listNode',
    getFn: 'readNode',
    kind: 'Node',
    namespaced: false,
  },
  pvs: {
    apiClass: 'CoreV1Api',
    listFn: 'listPersistentVolume',
    getFn: 'readPersistentVolume',
    replaceFn: 'replacePersistentVolume',
    deleteFn: 'deletePersistentVolume',
    kind: 'PersistentVolume',
    namespaced: false,
  },
  clusterroles: {
    apiClass: 'RbacAuthorizationV1Api',
    listFn: 'listClusterRole',
    getFn: 'readClusterRole',
    kind: 'ClusterRole',
    namespaced: false,
  },
  clusterrolebindings: {
    apiClass: 'RbacAuthorizationV1Api',
    listFn: 'listClusterRoleBinding',
    getFn: 'readClusterRoleBinding',
    kind: 'ClusterRoleBinding',
    namespaced: false,
  },
};

export function getResourceConfig(resourceType: string): ResourceConfig | undefined {
  return NAMESPACED_RESOURCES[resourceType] || CLUSTER_SCOPED_RESOURCES[resourceType];
}

export function isClusterScoped(resourceType: string): boolean {
  return resourceType in CLUSTER_SCOPED_RESOURCES;
}
